---
title: Анализ и визуализация многомерных данных с использованием R
description: Презентации к курсу Анализ и визуализация многомерных данных с использованием R
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
    theme: flatly
    highlight: haddock
    include:
      after_body: _footer.html
    css: my_styles.css
    lib_dir: site_libs
    self_contained: no
---
 
## О курсе

### Цель и задачи курса

Цель курса — научить решать с точки зрения статистики различные типы исследовательских задач в биологии (сравнение и группировка объектов; различение и разделение групп; определение места объекта/группы в ранее описанной системе). После освоения материалов курса вы сможете критически оценивать корректность применения методов статистики в научных статьях, самостоятельно анализировать данные с использованием скриптов на языке статистического программирования R, представлять в наглядном виде результаты анализов, интерпретировать их и представлять в виде научного отчета.

### Расписание и контакты

Начиная с февраля, 1--2й парой по понедельникам и четвергам

Инструкторы: 

- Варфоломеева Марина Александровна -  marina.varfolomeeva[]gmail.com
- Хайтов Вадим Михайлович - polydora[]rambler.ru
- Лянгузова Анастасия Дмитриевна


### Задания, дедлайны и оценки


(1) Тесты по каждой теме будут размещены на платформе Stepik.

(2) В конце курса будет финальный тест, тоже на Stepik.

Проценты будут пересчитаны в баллы по ECTS:  
50--60% --- E, 61--69% --- D, 70--79% --- C, 80--89% --- B, и наконец 90--100% --- это A по ECTS.

```{r echo=FALSE}
# Максимальный балл без пересдач (дз + финальный тест)
max_grade <- 209
# Ниж. границы оценок в долях от 1, начиная от самой плохой E
# Из приказа в Ун-те
breaks_prop <- c(0.5, 0.61, 0.7, 0.8, 0.9)
# Ниж. границы оценок в баллах
breaks_grade <- round(max_grade * breaks_prop, 1)
# Знаки неравенства для красоты
dividers <- c(paste( " \\le", LETTERS[5:2], "< "), " <= A")
# Границы оценок по ECTS
ECTS_string <- paste(breaks_grade, dividers, collapse = "")
# ECTS_string
# 104.5  <= E < 127.5  <= D < 146.3  <= C < 167.2  <= B < 188.1  <= A
# Генерируем формулу для Excel или Сalc для ячейки cell
cell <- "B4"
# cat(paste0('=ifs(', paste0(cell, ' < ', breaks_grade, ', "', c("Незачет", LETTERS[5:2]), collapse = '", '), '", ', cell, ' >= ', breaks_grade[5], ', "A")'))
# ФОРМУЛА
# =ifs(B4 < 104.5, "Незачет", B4 < 127.5, "E", B4 < 146.3, "D", B4 < 167.2, "C", B4 < 188.1, "B", B4 >= 188.1, "A")

```


Т.е. при максимальном балле `r max_grade`:  
$`r ECTS_string`$

## Ссылки и ресурсы

- [Правила хорошего кода](coding_practices.html)
- [Другие ресурсы и книги для изучения R и статистики](resources.html)


<br/>
<br/>
